'use client';

import Link from 'next/link';
import Image from 'next/image';
import { motion } from 'framer-motion';
import { useQuery } from '@tanstack/react-query';
import { ArrowUpRight, MapPin, Ruler } from 'lucide-react';
import { getMutation } from '@/lib/core/server';

interface Project {
  _id: string;
  title: string;
  shortDescription: string;
  image: string;
  area: number;
  buildingType: string;
  location: string;
  createdAt: string;
}

interface ProjectsResponse {
  success: boolean;
  data: Project[];
}

const containerVariants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.12 } },
} as const;

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { type: 'spring', stiffness: 90, damping: 18 },
  },
} as const;

function CardSkeleton() {
  return (
    <div className="bg-[#0F172A] border border-slate-800 rounded-2xl overflow-hidden h-[380px] animate-pulse flex flex-col">
      <div className="w-full h-48 bg-slate-800" />
      <div className="p-5 space-y-3 flex-1">
        <div className="h-5 bg-slate-800 rounded-md w-3/4" />
        <div className="h-4 bg-slate-800 rounded-md w-1/2" />
        <div className="h-4 bg-slate-800 rounded-md w-2/3" />
      </div>
    </div>
  );
}

export default function FeaturedProjectsSection() {
  const {
    data: projects = [],
    isLoading,
    isError,
  } = useQuery({
    queryKey: ['featured-projects'],
    queryFn: async (): Promise<Project[]> => {
      const res = await getMutation<ProjectsResponse>(
        '/api/projects?sortBy=newest',
      );
      if ('error' in res) {
        throw new Error(res.message || 'Failed to load projects.');
      }
      if (res.success && Array.isArray(res.data)) {
        return res.data.slice(0, 4);
      }
      throw new Error('Failed to load projects.');
    },
    staleTime: 1000 * 30,
  });

  if (!isLoading && !isError && projects.length === 0) {
    return null;
  }

  return (
    <section className="relative py-24 bg-[#020617] overflow-hidden">
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[60vw] h-[40vw] rounded-full bg-emerald-500/5 blur-[160px] pointer-events-none" />

      <div className="relative max-w-7xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.5 }}
          className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-12"
        >
          <div>
            <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-400 text-xs font-semibold mb-4">
              Live From The Platform
            </span>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#F8FAFC] tracking-tight">
              Recently Estimated Projects
            </h2>
            <p className="text-slate-400 mt-2 max-w-xl">
              Real cost estimates generated by our AI engine — explore what
              other builders are planning right now.
            </p>
          </div>
          <Link
            href="/explore"
            className="group inline-flex items-center gap-2 text-sm font-semibold text-[#38BDF8] hover:text-emerald-400 transition-colors whitespace-nowrap"
          >
            View All Projects
            <ArrowUpRight className="w-4 h-4 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
          </Link>
        </motion.div>

        {isLoading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {Array.from({ length: 4 }).map((_, idx) => (
              <CardSkeleton key={idx} />
            ))}
          </div>
        ) : isError ? (
          <div className="text-center py-16 bg-[#0F172A]/30 border border-slate-800/50 rounded-2xl text-slate-400">
            Couldn&apos;t load recent projects right now.
          </div>
        ) : (
          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-100px' }}
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"
          >
            {projects.map(project => (
              <motion.div key={project._id} variants={cardVariants}>
                <Link
                  href={`/explore/${project._id}`}
                  className="group block bg-[#0F172A] border border-slate-800 hover:border-emerald-500/40 rounded-2xl overflow-hidden h-[380px] flex flex-col transition-all duration-300 hover:shadow-[0_0_25px_rgba(16,185,129,0.12)]"
                >
                  <div className="relative w-full h-48 overflow-hidden bg-slate-900 flex-shrink-0">
                    <Image
                      src={project.image}
                      alt={project.title}
                      fill
                      sizes="(max-width: 768px) 100vw, 25vw"
                      className="object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <span className="absolute top-3 left-3 px-2.5 py-1 text-[11px] font-semibold rounded-full bg-[#020617]/80 backdrop-blur-sm text-emerald-400 border border-emerald-500/20 uppercase tracking-wide">
                      {project.buildingType}
                    </span>
                  </div>

                  <div className="p-5 flex flex-col flex-1">
                    <h3 className="text-base font-bold text-[#F8FAFC] line-clamp-1 group-hover:text-emerald-400 transition-colors">
                      {project.title}
                    </h3>
                    <p className="text-sm text-slate-400 mt-1.5 line-clamp-2 flex-1">
                      {project.shortDescription}
                    </p>

                    <div className="flex items-center justify-between mt-4 pt-4 border-t border-slate-800 text-xs text-slate-500">
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3.5 h-3.5" />
                        {project.location}
                      </span>
                      <span className="flex items-center gap-1">
                        <Ruler className="w-3.5 h-3.5" />
                        {project.area.toLocaleString()} sqft
                      </span>
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </motion.div>
        )}
      </div>
    </section>
  );
}
